### show all flight reservations
GET http://localhost:4434/flight/  HTTP/1.1
Accept: application/xml
### show all hotel reservations
GET http://localhost:4434/hotel  HTTP/1.1
Accept: application/xml

### create preliminary flight reservation
POST http://localhost:4434/flight  HTTP/1.1
Accept: application/xml
Content-Type: application/xml

<flightReservation date="1590307603704">
    <name>Christian</name>
    <from>Karlsruhe</from>
    <to>Berlin</to>
    <airline>airberlin</airline>
</flightReservation>
### create preliminary hotel reservation
POST http://localhost:4434/hotel  HTTP/1.1
Accept: application/xml
Content-Type: application/xml

<hotelReservation date="1590307603704">
    <name>Christian</name>
    <hotel>Interconti</hotel>
</hotelReservation>

### show flight reservation details
GET http://localhost:4434/flight/xyz  HTTP/1.1
Accept: application/xml
### show hotel reservation details
GET http://localhost:4434/hotel/xyz  HTTP/1.1
Accept: application/xml

### confirm flight reservation
PUT http://localhost:4434/flight/9dfb8ea2-50be-4707-a872-030719e75214  HTTP/1.1
Accept: text/plain
### confirm hotel reservation
PUT http://localhost:4434/hotel/e1848a59-0b4c-4926-9a32-5a51d3bee138  HTTP/1.1
Accept: text/plain
### cancel flight reservation
DELETE http://localhost:4434/flight/8675f522-b659-48e0-91fd-5b06115b512a  HTTP/1.1
Accept: text/plain
### cancel hotel reservation
DELETE http://localhost:4434/hotel/8adf3af8-d527-4ace-9ea3-dc789fb1e163  HTTP/1.1
Accept: text/plain
### show service description
GET http://localhost:4434/application.wadl HTTP/1.1
Accept: application/xml